<script setup lang="ts">
import { computed, toRef } from 'vue'
import type { Assessment, Constraint } from '@/types'
import { CATEGORY_LABELS, CATEGORY_ICONS } from '@/types'
import ConstraintCard from '@/components/ConstraintCard.vue'
import { api } from '@/services/api'
import { useComplianceCheck, type ProjectInputsModel } from '@/composables/useComplianceCheck'

const props = defineProps<{
  assessment: Assessment
  projectInputs?: ProjectInputsModel
  buildingType?: string
}>()

const complianceInputs = toRef(() => props.projectInputs ?? { stories: 1, bedrooms: 0, bathrooms: 0, sqft: null })
const complianceBuildingType = toRef(() => props.buildingType ?? 'SFH')
const complianceConstraints = toRef(() => props.assessment.constraints)
const lotArea = toRef(() => props.assessment.parcel.lot_area_sqft)

const { complianceMap } = useComplianceCheck(complianceInputs, complianceBuildingType, complianceConstraints, lotArea)

async function downloadGeojson() {
  try {
    const data = await api.geojson.export(props.assessment.id)
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/geo+json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `assessment-${props.assessment.id}.geojson`
    a.click()
    setTimeout(() => URL.revokeObjectURL(url), 200)
  } catch {
    console.warn('GeoJSON download failed')
  }
}

function downloadPdf() {
  const a = props.assessment
  const p = a.parcel
  const lines: string[] = []

  lines.push('ZONING ASSESSMENT REPORT')
  lines.push('=' .repeat(50))
  lines.push('')
  lines.push(`Address:      ${p.address || p.apn}`)
  lines.push(`Zone Code:    ${p.zone_code}`)
  lines.push(`Zone Class:   ${p.zone_class}`)
  if (p.lot_area_sqft) lines.push(`Lot Area:     ${p.lot_area_sqft.toLocaleString()} sqft`)
  lines.push(`Building Type: ${a.building_type}`)
  lines.push(`Confidence:   ${Math.round(a.overall_confidence * 100)}%`)
  lines.push(`Date:         ${new Date(a.created_at).toLocaleDateString()}`)
  lines.push('')

  if (a.warnings?.length) {
    lines.push('WARNINGS')
    lines.push('-'.repeat(50))
    for (const w of a.warnings) lines.push(`  ⚠ ${w}`)
    lines.push('')
  }

  lines.push('CONSTRAINTS')
  lines.push('-'.repeat(50))

  const grouped: Record<string, Constraint[]> = {}
  for (const c of a.constraints) {
    if (!grouped[c.category]) grouped[c.category] = []
    grouped[c.category].push(c)
  }

  for (const [cat, constraints] of Object.entries(grouped)) {
    lines.push('')
    lines.push(`  ${(CATEGORY_LABELS[cat] || cat).toUpperCase()}`)
    for (const c of constraints) {
      const val = c.value || (c.numeric_value != null ? `${c.numeric_value} ${c.unit || ''}` : '')
      lines.push(`    ${c.parameter}: ${val}`)
      if (c.rule_text) lines.push(`      Rule: ${c.rule_text}`)
      if (c.citations?.length) {
        lines.push(`      Section: ${c.citations[0].section_number}`)
      }
    }
  }

  lines.push('')
  lines.push('-'.repeat(50))
  lines.push('Generated by Cover Regulatory Engine')
  lines.push(`Assessment ID: ${a.id}`)

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const el = document.createElement('a')
  el.href = url
  el.download = `assessment-${p.address || p.apn}-${a.building_type}.txt`
  el.click()
  setTimeout(() => URL.revokeObjectURL(url), 200)
}

const groupedConstraints = computed(() => {
  const groups: Record<string, Constraint[]> = {}
  for (const c of props.assessment.constraints) {
    const cat = c.category
    if (!groups[cat]) groups[cat] = []
    groups[cat].push(c)
  }
  const order = ['setback', 'height', 'far', 'density', 'lot', 'use', 'parking', 'adu', 'coverage', 'other']
  const sorted: [string, Constraint[]][] = []
  for (const cat of order) {
    if (groups[cat]) sorted.push([cat, groups[cat]])
  }
  for (const [cat, items] of Object.entries(groups)) {
    if (!order.includes(cat)) sorted.push([cat, items])
  }
  return sorted
})

const deterministicCount = computed(() =>
  props.assessment.constraints.filter(c => c.determination_type === 'deterministic').length
)

const interpretedCount = computed(() =>
  props.assessment.constraints.filter(c => c.determination_type !== 'deterministic').length
)

const confidenceColor = computed(() => {
  const c = props.assessment.overall_confidence
  if (c >= 0.9) return 'text-cover-green'
  if (c >= 0.7) return 'text-accent'
  return 'text-cover-red'
})

const timeAgo = computed(() => {
  const created = new Date(props.assessment.created_at)
  const now = new Date()
  const diffMs = now.getTime() - created.getTime()
  const mins = Math.floor(diffMs / 60000)
  if (mins < 1) return 'Just now'
  if (mins < 60) return `${mins}m ago`
  const hrs = Math.floor(mins / 60)
  if (hrs < 24) return `${hrs}h ago`
  const days = Math.floor(hrs / 24)
  if (days < 7) return `${days}d ago`
  return created.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })
})
</script>

<template>
  <div class="divide-y divide-surface-200/50">
    <!-- Warnings -->
    <div v-if="assessment.warnings?.length" class="px-6 py-3">
      <div
        v-for="(warning, i) in assessment.warnings"
        :key="i"
        class="flex items-start gap-2 bg-amber-50 border border-amber-200 rounded-lg px-3.5 py-2.5 mb-2 last:mb-0"
      >
        <svg class="w-4 h-4 text-amber-500 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
        </svg>
        <p class="text-[12px] text-amber-800 leading-relaxed">{{ warning }}</p>
      </div>
    </div>

    <!-- Header -->
    <div class="px-6 py-4 bg-surface-50">
      <div class="flex items-start justify-between">
        <div>
          <h2 class="text-[14px] font-semibold text-cover-black tracking-tight">
            {{ assessment.parcel.address || assessment.parcel.apn }}
          </h2>
          <p class="text-[11px] text-surface-400 mt-1">
            Zone: <span class="font-semibold text-surface-500">{{ assessment.parcel.zone_code }}</span>
            <span v-if="assessment.parcel.lot_area_sqft" class="ml-3">
              Lot: <span class="font-semibold text-surface-500">{{ assessment.parcel.lot_area_sqft.toLocaleString() }} sqft</span>
            </span>
          </p>
        </div>
        <div class="text-right">
          <div :class="['text-[22px] font-bold tracking-tight', confidenceColor]">
            {{ Math.round(assessment.overall_confidence * 100) }}%
          </div>
          <div class="text-[9px] font-semibold uppercase tracking-widest text-surface-400">Confidence</div>
        </div>
      </div>

      <div class="flex items-center gap-2 mt-3">
        <span class="badge-deterministic">
          {{ deterministicCount }} deterministic
        </span>
        <span v-if="interpretedCount > 0" class="badge-interpreted">
          {{ interpretedCount }} interpreted
        </span>
        <span class="text-[11px] text-surface-400">
          {{ assessment.building_type }}
        </span>
        <span class="text-[10px] text-surface-300" :title="new Date(assessment.created_at).toLocaleString()">
          · {{ timeAgo }}
        </span>
        <div class="ml-auto flex items-center gap-1.5">
          <button
            @click="downloadPdf"
            class="flex items-center gap-1.5 px-2.5 py-1 text-[10px] font-medium text-surface-400 hover:text-cover-black border border-surface-200 hover:border-surface-400 rounded transition-colors"
            title="Download assessment report"
          >
            <svg class="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
            </svg>
            Report
          </button>
          <button
            @click="downloadGeojson"
            class="flex items-center gap-1.5 px-2.5 py-1 text-[10px] font-medium text-surface-400 hover:text-cover-black border border-surface-200 hover:border-surface-400 rounded transition-colors"
            title="Download assessment as GeoJSON"
          >
            <svg class="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            GeoJSON
          </button>
        </div>
      </div>
    </div>

    <!-- Empty constraints state -->
    <div v-if="assessment.constraints.length === 0" class="px-6 py-8 text-center">
      <svg class="w-10 h-10 mx-auto text-surface-200 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
      </svg>
      <p class="text-[13px] font-medium text-surface-400">No constraints available</p>
      <p class="text-[11px] text-surface-300 mt-1">Zone rules for this zone class have not been loaded yet.</p>
    </div>

    <!-- Constraint groups -->
    <div v-for="[category, constraints] in groupedConstraints" :key="category" class="px-6 py-4">
      <h3 class="text-[9px] font-bold uppercase tracking-widest-plus text-surface-400 mb-2.5 flex items-center gap-1.5">
        <span>{{ CATEGORY_ICONS[category] || '•' }}</span>
        {{ CATEGORY_LABELS[category] || category }}
        <span class="text-surface-300 font-normal">({{ constraints.length }})</span>
      </h3>
      <div class="space-y-2">
        <ConstraintCard
          v-for="constraint in constraints"
          :key="constraint.id"
          :constraint="constraint"
          :assessment-id="assessment.id"
          :compliance="complianceMap.get(constraint.id)"
        />
      </div>
    </div>
  </div>
</template>
